/**
 * Movie Search API
 * This is a simple movie search API, with caching. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Movie } from './movie';


export interface PaginatedMovies { 
    page: number;
    total_pages: number;
    total_results: number;
    cache_hit: number;
    cached_at: number;
    results: Array<Movie>;
}

